services:
  minio:
    image: bitnami/minio:2024
    networks: [ 'kkp' ]
    volumes: [ 'minio_data:/data' ]
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SERVER_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${S3_BUCKET_NAME}
      - MINIO_SERVER_URL=http://minio:9000
      - MINIO_SERVER_HOST=${S3_ENDPOINT_PUBLIC}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
      #- BITNAMI_DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: mc ready local
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  mariadb:
    image: mariadb:10.6
    networks: [ 'kkp' ]
    volumes: [ 'mariadb_data:/var/lib/mysql' ]
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=kkp
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:latest
    networks: [ 'kkp' ]
    restart: unless-stopped
    healthcheck:
      test: redis-cli --raw incr ping
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 15
  mailcatcher:
    image: schickling/mailcatcher:latest
    networks: [ 'kkp' ]
    restart: unless-stopped
    healthcheck:
      test: wget --spider --server-response --quiet "http://127.0.0.1:1080/messages" 2>&1 | grep "200 OK"
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 15
  kkp-api:
    build: .
    pull_policy: build
    networks: [ 'kkp' ]
    volumes: [ '${MIGRATIONS_VOLUME}:/migrations' ]
    environment:
      - DB_CONNECTION_STRING=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb/kkp
      - MIGRATIONS_DIR=/migrations/kkp
      - S3_ENDPOINT=http://minio:9000
      - S3_ENDPOINT_PUBLIC=${S3_ENDPOINT_PUBLIC}
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_ACCESS_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - ROOT_PATH=/api
      - JWT_KEY=${JWT_KEY}
      - JWT_TTL=${JWT_TTL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GOOGLE_REDIRECT=${OAUTH_GOOGLE_REDIRECT}
      - PAYPAL_ID=${PAYPAL_ID}
      - PAYPAL_SECRET=${PAYPAL_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOGURU_LEVEL=DEBUG
      - PUBLIC_HOST=${PUBLIC_HOST}
    depends_on:
      mariadb:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailcatcher:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/health || exit 1
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
  nginx:
    image: nginx
    ports:
      - '${NGINX_ADDRESS}:80'
    networks: [ 'kkp' ]
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      kkp-api:
        condition: service_healthy
    restart: unless-stopped
  mariadb-backups:
    image: databack/mysql-backup
    command: dump --frequency=60
    networks: [ 'kkp' ]
    environment:
      - DB_DUMP_FREQUENCY=720
      - DB_DUMP_TARGET=${BACKUPS_S3_TARGET}
      - AWS_ACCESS_KEY_ID=${BACKUPS_S3_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BACKUPS_S3_SECRET_ACCESS_KEY}
      - AWS_REGION=${BACKUPS_S3_REGION}
      - AWS_ENDPOINT_URL=${BACKUPS_S3_ENDPOINT_URL}
      - AWS_PATH_STYLE=${BACKUPS_S3_PATH_STYLE}
      - DB_SERVER=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

networks:
  kkp:
    driver: bridge

volumes:
  minio_data:
    driver: local
  mariadb_data:
    driver: local
  migrations:
    driver: local